import type { Metadata } from "next";
import { Archive, FileInput, Scale, ShieldCheck } from "lucide-react";
import { FlowMap } from "../flow-map";
import { LegalPage } from "../legal-page";

export const metadata: Metadata = { title: "Privacidade" };

export default function PrivacyPage() {
  return <LegalPage title="Política de privacidade" lead="Como o Maiocchi Advogado trata dados pessoais durante a preparação e a assinatura de documentos." currentPath="/privacidade/">
    <p className="legal-meta">Versão de 15 de julho de 2026.</p>
    <FlowMap eyebrow="Ciclo dos dados" title="Finalidade do início ao encerramento." description="O tratamento acompanha o serviço jurídico, com acesso limitado, segurança proporcional e retenção justificada." ariaLabel="Ciclo de tratamento de dados pessoais no portal" steps={[
      { title: "Coletar o necessário", description: "Dados entram pelo documento, convite, assinatura e suporte, sempre de forma limitada.", icon: FileInput },
      { title: "Usar com finalidade", description: "O tratamento serve ao fluxo, à evidência e aos deveres profissionais.", icon: Scale, tone: "yellow" },
      { title: "Proteger e limitar", description: "Acesso, isolamento e controles reduzem exposição indevida.", icon: ShieldCheck },
      { title: "Reter ou eliminar", description: "Prazos consideram serviço, lei, direitos e cópias de segurança.", icon: Archive },
    ]} />
    <h2>1. Controlador e contato</h2><p>O tratamento é realizado no contexto da atividade profissional do Maiocchi Advogado, sob responsabilidade de Roger Maiocchi, OAB/DF 31.249. Solicitações de titulares e comunicações de privacidade devem ser encaminhadas pela <a href="/ajuda/">Central de ajuda</a>.</p>
    <h2>2. Alcance</h2><p>Esta política abrange o portal público, o ambiente DocuSeal, convites, preenchimento, assinaturas, validação, suporte e registros técnicos associados. Sites oficiais ou serviços externos acessados por link possuem políticas próprias.</p>
    <h2>3. Dados tratados</h2><p>Podem ser tratados nome, contato, função, dados de identificação presentes no documento, conteúdo documental, campos preenchidos, assinatura desenhada, certificado público, resultado de validação, eventos e comunicações de suporte. Ao iniciar uma assinatura remota, o servidor deriva o endereço IP da conexão e registra data e hora; o navegador envia user agent, plataforma, fuso horário, idioma e dimensões da tela. A localização é opcional: latitude, longitude e precisão somente são recebidas quando o titular autoriza expressamente o navegador, e a recusa ou indisponibilidade não impede a assinatura. A verificação acessível a quem possui o ID opaco exibe hashes, perfil, política, horários, resultado técnico, nome do signatário e CPF mascarado; não expõe o certificado completo nem a chave pública individual do titular.</p>
    <h2>4. Dados de maior risco</h2><p>Documentos jurídicos podem conter dados sensíveis, financeiros, de crianças, informações processuais ou conteúdo protegido por segredo profissional. O acesso é limitado ao fluxo e às pessoas autorizadas.</p>
    <h2>5. Finalidades</h2><p>Os dados são usados para preparar o documento, identificar participantes, entregar acesso, coletar manifestação de vontade, produzir evidências, validar assinaturas, disponibilizar a cópia final, prevenir abuso, atender solicitações e cumprir deveres legais e profissionais. IP, data e hora, ambiente do navegador e eventual localização autorizada são tratados exclusivamente para compor o contexto probatório da assinatura e proteger o fluxo contra fraude, uso indevido e incidentes de segurança. São coletados somente os campos necessários a essas finalidades, sem perfil comportamental ou enriquecimento de localização.</p>
    <h2>6. Bases legais</h2><p>Conforme o contexto, o tratamento pode decorrer de execução de contrato ou procedimentos preliminares, cumprimento de obrigação legal ou regulatória, exercício regular de direitos e legítimo interesse avaliado. Consentimento será solicitado apenas quando for a base adequada, de forma específica e revogável.</p>
    <h2>7. Compartilhamento</h2><p>A Hostinger processa dados para operar a VPS e a Apple iCloud Mail transporta códigos e alertas sem documento anexo. O DocuSeal e o serviço criptográfico são autogeridos na VPS: o uso desses programas não envia documentos aos seus mantenedores. O provider remoto de assinatura permanece desabilitado e recebe zero bytes até eventual contratação e avaliação formal. Não vendemos dados nem os usamos para publicidade comportamental.</p>
    <h2>8. Transferência internacional</h2><p>Os dados principais do portal permanecem na VPS contratada. O transporte de e-mail pode utilizar a infraestrutura internacional do provedor contratado. Qualquer novo processamento internacional material exige avaliação de finalidade, segurança, garantias aplicáveis e atualização desta política antes da ativação.</p>
    <h2>9. Retenção</h2><p>Como padrões internos de governança, desafios de login expirados são eliminados no ciclo horário; tickets de assinatura não concluídos entram em saneamento a partir de 30 dias e seus bytes sem referência somente são eliminados depois de backup cifrado confirmado fora da VPS; convites, sessões e rascunhos encerrados, após 90 dias; e logs de segurança sem incidente, após 180 dias. Backups cifrados expiram em 35 dias. Documentos concluídos, assinaturas e evidências não entram em limpeza automática e são revistos, por padrão, dez anos após o encerramento do expediente. Registros de incidentes são preservados por no mínimo cinco anos. Obrigação legal, segredo profissional, exercício de direitos e ordem de preservação podem alterar esses prazos e suspendem o descarte.</p>
    <h2>10. Segurança</h2><p>São empregados HTTPS, controles de acesso, isolamento de serviços, trilha de eventos, armazenamento por conteúdo, verificação de hashes, limitação de requisições e atualização de componentes. Artefatos criptográficos usam cifragem autenticada em repouso e o backup é cifrado antes de ser gravado. O original eletrônico é restrito por padrão. Nenhum sistema elimina todo risco; incidentes devem ser comunicados imediatamente pelo canal informado.</p>
    <h2>11. Certificados digitais</h2><p>Chave privada, arquivo A1, PIN e senha não devem ingressar no portal. A operação criptográfica do certificado permanece no dispositivo ou serviço controlado pelo titular. O sistema pode tratar apenas dados públicos do certificado e o resultado da validação.</p>
    <h2>12. Direitos do titular</h2><p>O titular pode solicitar confirmação, acesso, correção, informação sobre compartilhamento, anonimização, bloqueio, eliminação quando cabível, portabilidade nos termos regulamentares, oposição e revisão de decisão automatizada, se houver. A identidade do requerente poderá ser verificada antes da resposta.</p>
    <h2>13. Verificação de autenticidade</h2><p>Ao selecionar um PDF na página de validação, o navegador calcula o SHA-256 localmente e não envia o arquivo ao portal. O serviço pode receber somente o resultado de correspondência ou divergência, associado ao ID opaco e ao horário. O acesso voluntário ao VALIDAR ITI transfere o arquivo ao serviço oficial segundo seus próprios termos e política.</p>
    <h2>14. Decisões automatizadas</h2><p>O portal não usa perfil comportamental nem inteligência artificial para declarar validade jurídica, escolher certificado ou operar chave privada. Resultados criptográficos inválidos ou indeterminados bloqueiam o fluxo e exigem revisão humana.</p>
    <h2>15. Incidentes</h2><p>Incidentes são avaliados quanto à confirmação, natureza dos dados, alcance e risco ou dano relevante. Quando a legislação exigir, o controlador comunicará a ANPD e os titulares em até três dias úteis, ressalvado prazo específico, com contenção, mitigação e complementação fundamentada quando necessária.</p>
    <h2>16. Atualizações</h2><p>Esta política será revista quando o fluxo, os fornecedores ou a legislação mudarem. A versão vigente permanecerá disponível nesta página.</p>
    <h2>17. Fontes legais</h2><p>Consulte a <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm" target="_blank" rel="noreferrer">Lei Geral de Proteção de Dados Pessoais</a>, a <a href="https://www.gov.br/anpd/pt-br/acesso-a-informacao/institucional/atos-normativos/regulamentacoes_anpd/resolucao-cd-anpd-no-2-de-27-de-janeiro-de-2022" target="_blank" rel="noreferrer">Resolução CD/ANPD nº 2/2022</a> e o <a href="https://www.gov.br/anpd/pt-br/canais_atendimento/agente-de-tratamento/comunicado-de-incidente-de-seguranca-cis" target="_blank" rel="noreferrer">procedimento oficial de incidentes da ANPD</a>.</p>
  </LegalPage>;
}
